language: node_js
node_js:
- '8'
dist: trusty
sudo: false
branches:
  only:
  - master
cache:
  directories:
  - node_modules
addons:
  chrome: stable
script:
- npm run lint
- npm run test:headless
- npm run build
- xvfb-run npm run e2e
deploy:
  provider: heroku
  api_key:
    secure: k8G14jJNWHu7mnhD2UpPaanCZ5MJJ2Yp5JwZgzoHBYIoESKbsQbZKiUYoJQ1/WwcS+16BS7d0pMsrRQv/915vkHMG6AHWEhOLpzLI/4TfPW2KW5c8ilcjZZjlouKiam/fCgxDMmR1MkERaIM7i3FYbRZN9RIU/kjatOT2rmUASlSN2t7kRUSXRSa6drZExQTqh8KqO3CPgYfLeFXvJVxuqhFHlGiKBkO+CrxJYUCtoyucP71XQkn7ZVdZ0eG3ge0bgT+UWEjw3/aKTOi5eM5UTOrVbZYUNxWADHpnXLv24aS+IPnoj7xmuWXv/M69u7Y2x3wv7NAjELr86zQE6NJJSCaLE/xyxVidJzx4jrb5JzMxqaZNq7V6CLypHsT2UwtJ9c39OeE6ls7UzLgiYHr/SR8x+pbOvkt3e5f5YkWfxpUiRC1pdsNy91EFz2Unpc280+XFLgsAZxNGy2kS5GFWHZJ6UU7kQzyysfnTqTe7reBynQTrnSoX5QRWPvoqSN2ZAzKVZf+4UG4v2cH93ig7Hi4gfxDOwcnBEd73b0a0zFwXrpLPKMAiHE14Kq2Y7lNvK0dYsOugTmxgCLp7/yGS2RgpY6/0Pqnqxcx7YRCCGTMkHURyHkLmlh7oJTsnmaLccge7AvL4YFAKMbRKR4JF9ROry7C/MKh8q0JIIxH/cA=
  app: astrobot-dev-frontend