language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm run lint
  - npm run test --watch false -cc
  - npm run build
  - xvfb-run npm run e2e
